---
- name: Seting up the test hosts
  hosts: server01:server02
  become: yes
  tasks:
    - name: Dropping in config
      copy:
        src: lab2a-configurations/{{ansible_hostname}}/interfaces
        dest: /etc/network/interfaces
      notify: apply interface config

  handlers:
    - name: apply interface config
      service:
        name: networking
        state: restarted

