---
- name: Getting you ready for lab3
  hosts: server01:server02:leaf01:leaf02
  gather_facts: no
  become: yes
  tasks:
    - name: Dropping in config
      copy:
        src: lab3-configurations/{{inventory_hostname}}/interfaces
        dest: /etc/network/interfaces
      notify: apply interface config
   
  handlers:
    - name: apply interface config
      become: yes
      command: ifreload -a

