---
- hosts: localhost:server01:server02:leaf01:leaf02:spine01
  gather_facts: no
  tasks:
    - name: remove netq
      become: yes
      apt:
        name:
          - netq-apps
          - netq-agent
        state: absent
  
- hosts: localhost
  gather_facts: no
  tasks:
    - name: place license on webserver
      become: yes
      copy:
        src: license.lic
        dest: /var/www/html/license.lic
        mode: '0644'
        
- hosts: server01:server02
  gather_facts: no
  tasks:
    - name: Setting up the test hosts config
      become: yes
      copy:
        src: lab2-configurations/{{inventory_hostname}}/interfaces
        dest: /etc/network/interfaces
      notify: apply interface config

    - name: install traceroute
      become: yes
      apt:
        name: traceroute
        state: present
                
    - name: flush arp
      become: yes
      command: ip -s -s neigh flush all
      no_log: true

  handlers:
    - name: apply interface config
      become: yes
      command: ifreload -a
